# Generated by Django 2.1.4 on 2019-01-26 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='max_fertility',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='max_moist',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='max_ph',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='min_fertility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='min_moist',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='min_ph',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
    ]
