# Generated by Django 2.1.4 on 2019-01-26 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190126_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='max_fertility',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='max_moist',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='max_ph',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=10, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='min_fertility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='min_moist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='min_ph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
    ]
