# Generated by Django 2.1.7 on 2019-03-06 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190208_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpkPerPh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('n_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
                ('p_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
                ('k_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlantMoistLvl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_moist_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('max_moist_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], default='high', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlantPh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_ph', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('max_ph', models.DecimalField(decimal_places=2, default=14, max_digits=10, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recco_n_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
                ('recco_p_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
                ('recco_k_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
                ('npk_match_ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NpkPerPh')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('good_for_min_moist_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
                ('good_for_max_moist_lvl', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='sensorrecord',
            old_name='record_time',
            new_name='record_date',
        ),
        migrations.RenameField(
            model_name='sensorrecord',
            old_name='soil_profile',
            new_name='soil_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='max_fertility',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='max_moist',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='max_ph',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='min_fertility',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='min_moist',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='min_ph',
        ),
        migrations.RemoveField(
            model_name='sensorrecord',
            name='fertility',
        ),
        migrations.AlterField(
            model_name='sensorrecord',
            name='ph',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=10),
        ),
        migrations.AddField(
            model_name='recommendedplant',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Plant'),
        ),
        migrations.AddField(
            model_name='recommendedplant',
            name='recco_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Recommendation'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recco_soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SoilType'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='soil_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SoilProfile'),
        ),
    ]
