# Generated by Django 2.1.7 on 2019-03-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190306_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmoistlvl',
            name='max_moist_lvl',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('mid', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='very_high', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantmoistlvl',
            name='min_moist_lvl',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('mid', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='very_low', max_length=10),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='good_for_max_moist_lvl',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('mid', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='good_for_min_moist_lvl',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('mid', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=10),
        ),
    ]
