# Generated by Django 2.1.7 on 2019-03-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190306_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantmoistlvl',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plantph',
            name='name',
        ),
        migrations.AddField(
            model_name='plantmoistlvl',
            name='plant_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Plant'),
        ),
        migrations.AddField(
            model_name='plantph',
            name='plant_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Plant'),
        ),
    ]
