# Generated by Django 2.1.7 on 2019-03-09 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190309_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npkperph',
            name='ph',
        ),
        migrations.AddField(
            model_name='npkperph',
            name='max_ph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='npkperph',
            name='min_ph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
    ]
