# Generated by Django 2.1.7 on 2019-03-10 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190309_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recco_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
