# Generated by Django 2.1.7 on 2019-03-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_recommendation_recco_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recco_soil_type',
        ),
        migrations.AddField(
            model_name='recommendedplant',
            name='recco_soil_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.SoilType'),
        ),
    ]
