# Generated by Django 2.1.7 on 2019-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190310_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npkperph',
            name='k_lvl',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='npkperph',
            name='n_lvl',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='npkperph',
            name='p_lvl',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='plantmoistlvl',
            name='max_moist_lvl',
            field=models.IntegerField(choices=[(0, 'Very Low'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')], default=4),
        ),
        migrations.AlterField(
            model_name='plantmoistlvl',
            name='min_moist_lvl',
            field=models.IntegerField(choices=[(0, 'Very Low'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')], default=0),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recco_k_lvl',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recco_n_lvl',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recco_p_lvl',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='good_for_max_moist_lvl',
            field=models.IntegerField(choices=[(0, 'Very Low'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')]),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='good_for_min_moist_lvl',
            field=models.IntegerField(choices=[(0, 'Very Low'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')]),
        ),
    ]
