# Generated by Django 2.1.7 on 2019-03-18 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190314_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorrecord',
            name='record_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
